### ISSUE TITLE
Ghost users logged in

### ISSUE THREAD

**Issue by BinaryNebula** [exaskye/Drogtor#4]
Hey really like the Mod! I did run into an issue. Using AMP instance manager and a Whitelist for logging in. 

If a user changes their name and signs out, the server does not recognize the user as signing off. So for example lets say my Username is Joseph and I use /nick Joe, when I sign onto the server the logs show Joseph as signing in, but show Joe as signing off. I have my limit set to 20 users able to log into the server. If 0 people are on the server and I log in it will show 1/20. When I log out it will still show 1/20. Then when I log back in it shows 2/20, log out it stays 2/20. Repeat until 20/20 and no one can login despite the server actually being empty.

**Comment by exaskye** [comment]
The only potential workaround for logscrapers being confused by nick changing is a mixin to make the console always show the player's true username. I'm tempted to call this "not my problem", but may implement that.
