### ISSUE TITLE
Request: Show nickname changes in server logs.

### ISSUE THREAD

**Issue by nycki93** [exaskye/Drogtor#6]
Just for my own peace of mind, I'd like to know as a server admin if a player changes their nickname. Currently I can see "X is now known as Y" in game, but not in the server log.

**Comment by ghost** [comment]
I recommend [CommandSpy](https://github.com/samolego/commandspy) by [samo_lego](https://github.com/samolego)
You can log all commands to the console and players in-game that you specify with LuckPerms or just all ops if you prefer.

**Comment by emilyastranova** [comment]
My pull request adds this feature:
![image](https://user-images.githubusercontent.com/16725119/145693117-0684c18c-bf71-45e0-adce-5198e2a40d81.png)

**Comment by exaskye** [comment]
Drogtor is in feature freeze and has been obsoleted by the PlaceholderAPI ecosystem, including Styled Nicknames. If you still want this, I encourage you to check if Styled Nicknames meets your needs, and if not, to request this feature over there.
